#!/bin/bash
brew install nuget
brew cask install mono-mdk
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
nuget restore "$SCRIPT_DIR/StyleCop.Baboon"
msbuild "$SCRIPT_DIR/StyleCop.Baboon/StyleCop.Baboon.sln"
echo "alias StyleCop='$SCRIPT_DIR/FindViolations'" >> ~/.bash_profile
source ~/.bash_profile
echo 'done'
